/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultJobIdRouteImport } from './routes/result.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultJobIdRoute = ResultJobIdRouteImport.update({
  id: '/result/$jobId',
  path: '/result/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jobs' | '/models' | '/settings' | '/result/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jobs' | '/models' | '/settings' | '/result/$jobId'
  id: '__root__' | '/' | '/jobs' | '/models' | '/settings' | '/result/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  ResultJobIdRoute: typeof ResultJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$jobId': {
      id: '/result/$jobId'
      path: '/result/$jobId'
      fullPath: '/result/$jobId'
      preLoaderRoute: typeof ResultJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  ResultJobIdRoute: ResultJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
